// <auto-generated />
using System;
using AcmeProxy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcmeProxy.Migrations
{
    [DbContext(typeof(AcmeProxyDbContext))]
    partial class AcmeProxyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AcmeProxy.Data.Entities.ClientAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeyJwkJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientAccounts");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.LeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountKeyPem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeAccounts");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateChainPem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("HestiaDnsRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TxtValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId")
                        .IsUnique();

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifiersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeOrderUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyAuthorization", b =>
                {
                    b.HasOne("AcmeProxy.Data.Entities.ProxyOrder", "Order")
                        .WithOne("Authorization")
                        .HasForeignKey("AcmeProxy.Data.Entities.ProxyAuthorization", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyCertificate", b =>
                {
                    b.HasOne("AcmeProxy.Data.Entities.ProxyOrder", "Order")
                        .WithOne("Certificate")
                        .HasForeignKey("AcmeProxy.Data.Entities.ProxyCertificate", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyChallenge", b =>
                {
                    b.HasOne("AcmeProxy.Data.Entities.ProxyAuthorization", "Authorization")
                        .WithOne("Challenge")
                        .HasForeignKey("AcmeProxy.Data.Entities.ProxyChallenge", "AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyAuthorization", b =>
                {
                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("AcmeProxy.Data.Entities.ProxyOrder", b =>
                {
                    b.Navigation("Authorization");

                    b.Navigation("Certificate");
                });
#pragma warning restore 612, 618
        }
    }
}
